
package Indah_Lestari_22220095;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author indah
 */
public class Mahasiswa extends javax.swing.JFrame {
    
    private Connection con;
    private Statement stat;
    private ResultSet res;
    /**
     * Creates new form Mahasiswa
     */
    
    public Mahasiswa() {
        initComponents();
        setTitle("FORM MAHASISWA");
        koneksi ();
        kosongkan ();       
    
    }
    private void koneksi (){
     try {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/database_m.rafli_mauludin", "root", "");
         stat=con.createStatement();
         } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);}   
    }
    private void kosongkan(){
     nim_text.setText("");
     nama.setText("");
     status.setSelectedIndex(-1);
     no_hp.setText("");
     alamat.setText("");
     nim_text.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        nim_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        no_hp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        hapus = new Indah_Lestari_22220095.button_image();
        simpan = new Indah_Lestari_22220095.button_image();
        search = new Indah_Lestari_22220095.button_image();
        lihat = new Indah_Lestari_22220095.button_image();
        menu = new javax.swing.JButton();
        button_image1 = new Indah_Lestari_22220095.button_image();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("DATA MAHASISWA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No.Handphone");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 140, 30));

        nim_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nim_textActionPerformed(evt);
            }
        });
        nim_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nim_textKeyTyped(evt);
            }
        });
        jPanel1.add(nim_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 140, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alamat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        no_hp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_hpActionPerformed(evt);
            }
        });
        no_hp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                no_hpKeyTyped(evt);
            }
        });
        jPanel1.add(no_hp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 140, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 140, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Kelamin");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));
        status.setSelectedIndex(-1);
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 140, 30));

        hapus.setForeground(new java.awt.Color(0, 0, 0));
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 80, 50));

        simpan.setForeground(new java.awt.Color(0, 0, 0));
        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 80, 50));

        search.setForeground(new java.awt.Color(0, 0, 0));
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 80, 50));

        lihat.setForeground(new java.awt.Color(0, 0, 0));
        lihat.setText("LIHAT");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });
        jPanel1.add(lihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 90, 50));

        menu.setBackground(new java.awt.Color(0, 0, 0));
        menu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        menu.setForeground(new java.awt.Color(0, 51, 204));
        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 80, 30));

        button_image1.setBackground(new java.awt.Color(204, 204, 0));
        button_image1.setForeground(new java.awt.Color(0, 0, 0));
        button_image1.setText("EDIT");
        button_image1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_image1ActionPerformed(evt);
            }
        });
        jPanel1.add(button_image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 90, 50));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 730, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_image1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_image1ActionPerformed
  int ok = JOptionPane.showConfirmDialog(null, "Apakah yakin ingin mengedit data?", "Confirmation", JOptionPane.YES_NO_OPTION);
try {
    if (ok == 0) {
        String sql = "UPDATE mahasiswa SET Nim=?, Nama=?, Jenis_Kelamin=?, No_Hp=?, Alamat=? WHERE Nim=?";
        PreparedStatement st = con.prepareStatement(sql);
        
        st.setString(1, nim_text.getText());
        st.setString(2, nama.getText());
        st.setString(3, (String) status.getSelectedItem());
        st.setString(4, no_hp.getText());
        st.setString(5, alamat.getText());
        st.setString(6, nim_text.getText()); // No untuk kondisi WHERE
        
        int result = st.executeUpdate();
        if (result > 0) {
            kosongkan();
            JOptionPane.showMessageDialog(null, "Edit Data Sukses");
            new Mahasiswa().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Tidak ada data yang diubah");
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Edit Data Gagal: " + e.getMessage());
}

    }//GEN-LAST:event_button_image1ActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        new main_menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_menuActionPerformed

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        // TODO add your handling code here:
        new TabelMahasiswa().setVisible(true);
        dispose();

    }//GEN-LAST:event_lihatActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
         try {
            res=stat.executeQuery("select * from mahasiswa where "+ "Nim='" +nim_text.getText()
            +"'" ); while (res.next())
                { nama.setText(res.getString("Nama"));
                status.setSelectedItem(res.getString("Jenis_Kelamin"));
                no_hp.setText(res.getString("No_Hp"));
                alamat.setText(res.getString("Alamat"));
    }
                }catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, e);
                    }
    }//GEN-LAST:event_searchActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        try {
         stat.executeUpdate("insert into mahasiswa values ("
             + "'" + nim_text.getText()+"',"
             + "'" + nama.getText()+"',"
             + "'" + status.getSelectedItem()+ "',"
             + "'" + no_hp.getText()+"',"
             + "'" + alamat.getText()+"')");
         kosongkan();
         JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
         new Mahasiswa().setVisible(true);
         dispose();
         } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Gagal Menyimpan Data! : "+e);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int ok=JOptionPane.showConfirmDialog(null, "Apakah yakin ingin menghapus?", "Confirmation", 
                JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0)
        {
         try{
             String sql="delete from mahasiswa where Nim='"+nim_text.getText()+"'";
             PreparedStatement st=con.prepareStatement (sql);
             st.executeUpdate();
             kosongkan();
             JOptionPane.showMessageDialog(null, "Delete Data Sukses");
             new Mahasiswa().setVisible(true);
             dispose();
         } catch (Exception e)
         {
             JOptionPane.showMessageDialog(null, "Delete Data Gagal" +e);
         }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void no_hpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_hpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_hpActionPerformed

    private void nim_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nim_textActionPerformed
        // TODO add your handling code here:
        try{
            res=stat.executeQuery("select * from mahasiswa where "+ "Nim='" + nim_text.getText()
                +"'" ); while (res.next())
                { nama.setText(res.getString("Nama"));
                status.setSelectedItem(res.getString("Jenis_Kelamin"));
                no_hp.setText(res.getString("No.Hp"));
                alamat.setText(res.getString("Alamat"));
                }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_nim_textActionPerformed

    private void nim_textKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nim_textKeyTyped
        // TODO add your handling code here:
        char rafli=evt.getKeyChar();
        if(!(Character.isDigit(rafli)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_nim_textKeyTyped

    private void no_hpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_hpKeyTyped
        // TODO add your handling code here:
        char rafli=evt.getKeyChar();
        if(!(Character.isDigit(rafli)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_no_hpKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField alamat;
    public Indah_Lestari_22220095.button_image button_image1;
    public Indah_Lestari_22220095.button_image hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public Indah_Lestari_22220095.button_image lihat;
    private javax.swing.JButton menu;
    public javax.swing.JTextField nama;
    public javax.swing.JTextField nim_text;
    public javax.swing.JTextField no_hp;
    public Indah_Lestari_22220095.button_image search;
    public Indah_Lestari_22220095.button_image simpan;
    public javax.swing.JComboBox<String> status;
    // End of variables declaration//GEN-END:variables
}
