/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Indah_Lestari_22220095;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.awt.event.KeyEvent;
import java.sql.Date;

/**
 *
 * @author Rafli
 */
public class Uang_Kas extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;
    private String t, penjelasan;
    private DefaultTableModel dtm;
    /**
     * Creates new form Uang_Kas
     */
    public Uang_Kas() {
        initComponents();
        setTitle("LAPORAN UANGKAS");
        koneksi ();
        kosongkan ();
        tabel ();
        //rata kiri dan kanan
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
           (screenSize.width - frameSize.width) / 3,
           (screenSize.height - frameSize.height) /4);
    }
private void koneksi (){
     try {
         con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/database_m.rafli_mauludin", "root", "");
         stat=con.createStatement();
         } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);}   
    }
    
    private void kosongkan(){
     No.setText("");
     Tanggal_Isi.setText(null);
     Tanggal_Isi.setText("");
     text_keterangan.setText("");
     Uang_Pembayaran.setText("");
     Uang_Pengeluaran.setText("");
     Saldo_Akhir.setText("");
     jCheckBox1.setSelected(false);
     jCheckBox2.setSelected(false);
     No.requestFocus();
    }
    
    private void tabel (){
        DefaultTableModel t= new DefaultTableModel();
        t.addColumn("No");
        t.addColumn("Tanggal");
        t.addColumn("Nama");
        t.addColumn("Keterangan");
        t.addColumn("Pemasukan");
        t.addColumn("Pengeluaran");
        t.addColumn("Saldo_Akhir");
        Tabel.setModel(t); try{ res= stat.executeQuery("select * from uangkas");
    while (res.next()) {
    t.addRow(new Object[]{ 
      res.getString("No"),
      res.getString("Tanggal"),
      res.getString("Nama"),
      res.getString("Keterangan"),
      res.getString("Pemasukan"),
      res.getString("Pengeluaran"),
      res.getString("Saldo_Akhir")
        });}
}catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, e);}    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Menu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        No = new javax.swing.JTextField();
        Tanggal_Isi = new javax.swing.JTextField();
        text_keterangan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Uang_Pembayaran = new javax.swing.JTextField();
        Uang_Pengeluaran = new javax.swing.JTextField();
        Saldo_Akhir = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        Lihat = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        bg = new javax.swing.JLabel();
        Nama1 = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("LAPORAN KEUANGAN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        Menu.setText("Menu");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Keterangan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });
        No.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NoKeyTyped(evt);
            }
        });
        jPanel1.add(No, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 130, -1));

        Tanggal_Isi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tanggal_IsiActionPerformed(evt);
            }
        });
        jPanel1.add(Tanggal_Isi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, -1));
        jPanel1.add(text_keterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 130, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rp.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rp.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Saldo Akhir");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Uang Kas / Minggu");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        Uang_Pembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Uang_PembayaranKeyTyped(evt);
            }
        });
        jPanel1.add(Uang_Pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 140, -1));

        Uang_Pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uang_PengeluaranActionPerformed(evt);
            }
        });
        Uang_Pengeluaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Uang_PengeluaranKeyTyped(evt);
            }
        });
        jPanel1.add(Uang_Pengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 140, -1));

        Saldo_Akhir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Saldo_AkhirKeyTyped(evt);
            }
        });
        jPanel1.add(Saldo_Akhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 140, -1));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 140, -1));

        Lihat.setText("Lihat");
        Lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LihatActionPerformed(evt);
            }
        });
        jPanel1.add(Lihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 70, -1));

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel1.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 80, 30));

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        jPanel1.add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 80, 30));

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 80, 30));

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPanel1.add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 80, 30));

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 80, 30));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tabel);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 610, 110));

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Pemasukan");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Pengeluaran");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, -1, -1));
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nama1ActionPerformed(evt);
            }
        });
        jPanel1.add(Nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
         try{
            res=stat.executeQuery("select * from uangkas where "+ "No='" + No.getText()
                +"'" ); while (res.next())
                { 
                Tanggal_Isi.setText(res.getString("Tanggal"));
                Nama1.setText(res.getString("Nama"));
                Uang_Pembayaran.setText(res.getString("Pemasukan"));
                Uang_Pengeluaran.setText(res.getString("Pengeluaran"));
                Saldo_Akhir.setText(res.getString("Saldo_Akhir"));
                text_keterangan.setText(res.getString("Keterangan"));
                }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_NoActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
String tanggalInput = Tanggal_Isi.getText(); // Mengambil tanggal dari JTextField
String nama = Nama1.getText();
String keterangan = text_keterangan.getText();
String uangPembayaran = Uang_Pembayaran.getText();
String uangPengeluaran = Uang_Pengeluaran.getText();
String saldoAkhir = Saldo_Akhir.getText();

try {
    stat.executeUpdate("INSERT INTO uangkas VALUES ("
        + "'" + No.getText() + "'," // Menggunakan No.getText() sesuai dengan kode yang diberikan
        + "'" + tanggalInput + "'," // Menggunakan tanggalInput yang diambil dari JTextField
        + "'" + nama + "'," // Menggunakan nama yang diambil dari JTextField Nama1
        + "'" + keterangan + "',"
        + "'" + uangPembayaran + "',"
        + "'" + uangPengeluaran + "',"
        + "'" + saldoAkhir + "')");
    kosongkan();
    JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
    new Uang_Kas().setVisible(true);
    dispose();
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal Menyimpan Data! : " + e);
}

    }//GEN-LAST:event_SimpanActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
    int ok = JOptionPane.showConfirmDialog(null, "Apakah yakin ingin mengedit data?", "Confirmation", JOptionPane.YES_NO_OPTION);

if (ok == 0) {
    String Tanggal = Tanggal_Isi.getText(); // Mengambil tanggal dari JTextField langsung

    try {
        String sql = "update uangkas set No=?, Tanggal=?, Nama=?, Keterangan=?, Pemasukan=?, Pengeluaran=?, Saldo_Akhir=? where No=?";
        PreparedStatement st = con.prepareStatement(sql);

        st.setString(1, No.getText());
        st.setString(2, Tanggal); // Mengisi parameter Tanggal dengan nilai dari Tanggal_Isi.getText()
        st.setString(3, Nama1.getText()); // Mengisi parameter Nama dengan nilai dari Nama1.getText()
        st.setString(4, text_keterangan.getText());
        st.setString(5, Uang_Pembayaran.getText());
        st.setString(6, Uang_Pengeluaran.getText());
        st.setString(7, Saldo_Akhir.getText());
        st.setString(8, No.getText()); // No untuk kondisi WHERE

        int result = st.executeUpdate();

        if (result > 0) {
            kosongkan();
            JOptionPane.showMessageDialog(null, "Edit Data Sukses");
            new Uang_Kas().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Edit Data Gagal");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Edit Data Gagal: " + e.getMessage());
    }
}


    }//GEN-LAST:event_EditActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
         int ok=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin menghapus data?","Confirmation",
                JOptionPane.YES_NO_OPTION);
         try{
             String sql="delete from uangkas where No='"+No.getText()+"'";
             PreparedStatement st=con.prepareStatement (sql);
             st.executeUpdate();
             kosongkan();
             JOptionPane.showMessageDialog(null, "Delete Data Sukses");
             new Uang_Kas().setVisible(true);
             dispose();
         } catch (Exception e)
         {
             JOptionPane.showMessageDialog(null, "Delete Data Gagal");
         }
    }//GEN-LAST:event_HapusActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_ClearActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        try {
    res = stat.executeQuery("SELECT * FROM uangkas WHERE No='" + No.getText() + "'");
    if (res.next()) {
        Tanggal_Isi.setText(res.getString("Tanggal"));
        Nama1.setText(res.getString("Nama"));
        Uang_Pembayaran.setText(res.getString("Pemasukan"));
        Uang_Pengeluaran.setText(res.getString("Pengeluaran"));
        Saldo_Akhir.setText(res.getString("Saldo_Akhir"));
        text_keterangan.setText(res.getString("Keterangan"));
    } else {
        JOptionPane.showMessageDialog(rootPane, "Data tidak ditemukan");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, "Error: " + e.getMessage());
}

    }//GEN-LAST:event_SearchActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
         new main_menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuActionPerformed

    private void LihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LihatActionPerformed
        // TODO add your handling code here:
        new TabelMahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_LihatActionPerformed

    private void TabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelMouseClicked
        // TODO add your handling code here:
        int i = Tabel.getSelectedRow();
    if(i==-1){
    return;
    }
    String code = (String)Tabel.getValueAt(i,0);
    String code1 = (String)Tabel.getValueAt(i,1);
    String code2 = (String)Tabel.getValueAt(i,2);
    String code3 = (String)Tabel.getValueAt(i,3);
    String code4 = (String)Tabel.getValueAt(i,4);
    String code5 = (String)Tabel.getValueAt(i,5);
    String code6 = (String)Tabel.getValueAt(i,6);
    
    No.setText(code);
    Tanggal_Isi.setText(code1);
    Nama1.setText(code2);
    text_keterangan.setText(code3);
    Uang_Pembayaran.setText(code4);
    Uang_Pengeluaran.setText(code5);
    Saldo_Akhir.setText(code6);
    }//GEN-LAST:event_TabelMouseClicked

    private void Uang_PembayaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Uang_PembayaranKeyTyped
        // TODO add your handling code here:
        char rafli=evt.getKeyChar();
        if(!(Character.isDigit(rafli)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_Uang_PembayaranKeyTyped

    private void Uang_PengeluaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Uang_PengeluaranKeyTyped
        // TODO add your handling code here:
         char rafli=evt.getKeyChar();
        if(!(Character.isDigit(rafli)))
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_Uang_PengeluaranKeyTyped

    private void Saldo_AkhirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Saldo_AkhirKeyTyped
        // TODO add your handling code here:
         char rafli=evt.getKeyChar();
        if(!(Character.isDigit(rafli)))
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_Saldo_AkhirKeyTyped

    private void NoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoKeyTyped
        // TODO add your handling code here:
       char rafli=evt.getKeyChar();
        if(!(Character.isDigit(rafli)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_NoKeyTyped

    private void Uang_PengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uang_PengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Uang_PengeluaranActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        penjelasan = "Uang Masuk";
        jCheckBox1.setSelected(true);
        text_keterangan.setText(""+penjelasan);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
         penjelasan = "Uang Keluar";
        jCheckBox2.setSelected(true);
        text_keterangan.setText(""+penjelasan);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void Tanggal_IsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tanggal_IsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tanggal_IsiActionPerformed

    private void Nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nama1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uang_Kas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uang_Kas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uang_Kas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uang_Kas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uang_Kas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Lihat;
    private javax.swing.JButton Menu;
    public javax.swing.JTextField Nama1;
    private javax.swing.JTextField No;
    private javax.swing.JTextField Saldo_Akhir;
    private javax.swing.JButton Search;
    private javax.swing.JButton Simpan;
    private javax.swing.JTable Tabel;
    public javax.swing.JTextField Tanggal_Isi;
    private javax.swing.JTextField Uang_Pembayaran;
    private javax.swing.JTextField Uang_Pengeluaran;
    private javax.swing.JLabel bg;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField text_keterangan;
    // End of variables declaration//GEN-END:variables
}
